org: testdevelopment
app: demo-cards-api
service: cards-api-demo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    apiKeySourceType: HEADER
    apiKeys:
      - value: ${ssm:api_key}
        description: Testing api key
        customerId: 221
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:us-east-1:485585223748:table/demo.cards.api
    - Effect: Allow
      Action:
        - ssm:Describe*
        - ssm:Get*
        - ssm:List*
      Resource:
        - arn:aws:ssm:us-east-1:485585223748:parameter/api_key

functions:
  setCardData:
    handler: src/handlers/setCardData/setCardData.handler
    events:
      - http:
          path: /widget
          method: post
          private: true
      - cloudwatchLog:
          logGroup: '/aws/lambda/setCardData'
  fetchCardData:
    handler: src/handlers/fetchCardData/fetchCardData.handler
    events:
      - http:
          path: /results
          method: post
          private: true
      - cloudwatchLog:
          logGroup: '/aws/lambda/fetchCardData'

resources:
  Resources:
    CardDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: demo.cards.api
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: expireIn
          Enabled: true

